#!perl
use 5.10.0;
use strict;
use warnings;

# ABSTRACT: Mojo app for hosting Badge::Depot badges
# AUTHORITY
# PODNAME: badge-depot-app
our $VERSION = '0.0004';

use Mojolicious::Lite;
use Module::Find qw/findallmod/;
use File::HomeDir qw/my_dist_data/;
use Path::Tiny;

unshift @{ app->plugins->namespaces }  => 'Badge::Depot::App::Plugin';
unshift @{ app->commands->namespaces } => 'Badge::Depot::App::Command';

plugin 'DB';
my $data_dir = path(my_dist_data('Badge-Depot-App'));
app->secrets([split /,/ => $data_dir->child('mojo.secrets')->slurp]);
plugin Config => { file => $data_dir->child('mojo.conf')->realpath };

my @badge_plugins = findallmod Badge::Depot::App::Plugin::Badge;

for my $plugin (@badge_plugins) {
    $plugin =~ s{^Badge::Depot::App::Plugin::}{};
    plugin $plugin;
}

get '/*' => sub {
    my $c = shift;
    my $whatev = $c->param('whatev');
    $c->reply->not_found;
};

app->start;

__END__

=pod

=head1 SYNOPSIS

    use Badge::Depot::App;

=head1 DESCRIPTION

Badge::Depot::App is ...

=head1 SEE ALSO

=cut
